import angular from 'angular';
// Import our app config files
import appConfig from './config/app.config';
import 'angular-ui-router';
// Import our templates file (generated by Gulp)
import './config/app.templates';
// Import our app functionaity
import './layout';
import './home';
// Create and bootstrap application
const requires = ['ui.router', 'templates', 'app.layout', 'app.home'];
// Mount on window for testing
window.app = angular.module('app', requires);
angular.module('app').config(appConfig);
angular.bootstrap(document, ['app'], {
  strictDi: true,
});
